//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UKM.ServiceAdmin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/UKMService")]
    [System.SerializableAttribute()]
    public partial class Account : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacultyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MajorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch {
            get {
                return this.BatchField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchField, value) != true)) {
                    this.BatchField = value;
                    this.RaisePropertyChanged("Batch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Faculty {
            get {
                return this.FacultyField;
            }
            set {
                if ((object.ReferenceEquals(this.FacultyField, value) != true)) {
                    this.FacultyField = value;
                    this.RaisePropertyChanged("Faculty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Major {
            get {
                return this.MajorField;
            }
            set {
                if ((object.ReferenceEquals(this.MajorField, value) != true)) {
                    this.MajorField = value;
                    this.RaisePropertyChanged("Major");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nim {
            get {
                return this.NimField;
            }
            set {
                if ((object.ReferenceEquals(this.NimField, value) != true)) {
                    this.NimField = value;
                    this.RaisePropertyChanged("Nim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StudentUKM", Namespace="http://schemas.datacontract.org/2004/07/UKMService")]
    [System.SerializableAttribute()]
    public partial class StudentUKM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UkmidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdAccount {
            get {
                return this.IdAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.IdAccountField, value) != true)) {
                    this.IdAccountField = value;
                    this.RaisePropertyChanged("IdAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ukmid {
            get {
                return this.UkmidField;
            }
            set {
                if ((object.ReferenceEquals(this.UkmidField, value) != true)) {
                    this.UkmidField = value;
                    this.RaisePropertyChanged("Ukmid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coach", Namespace="http://schemas.datacontract.org/2004/07/UKMService")]
    [System.SerializableAttribute()]
    public partial class Coach : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="cUkm", Namespace="http://schemas.datacontract.org/2004/07/UKMService")]
    [System.SerializableAttribute()]
    public partial class cUkm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdcoachField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UkmnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc {
            get {
                return this.DescField;
            }
            set {
                if ((object.ReferenceEquals(this.DescField, value) != true)) {
                    this.DescField = value;
                    this.RaisePropertyChanged("Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idcoach {
            get {
                return this.IdcoachField;
            }
            set {
                if ((object.ReferenceEquals(this.IdcoachField, value) != true)) {
                    this.IdcoachField = value;
                    this.RaisePropertyChanged("Idcoach");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ukmname {
            get {
                return this.UkmnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UkmnameField, value) != true)) {
                    this.UkmnameField = value;
                    this.RaisePropertyChanged("Ukmname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Place", Namespace="http://schemas.datacontract.org/2004/07/UKMService")]
    [System.SerializableAttribute()]
    public partial class Place : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Schedule", Namespace="http://schemas.datacontract.org/2004/07/UKMService")]
    [System.SerializableAttribute()]
    public partial class Schedule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndtimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdplaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StarttimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day {
            get {
                return this.DayField;
            }
            set {
                if ((object.ReferenceEquals(this.DayField, value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endtime {
            get {
                return this.EndtimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndtimeField, value) != true)) {
                    this.EndtimeField = value;
                    this.RaisePropertyChanged("Endtime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idplace {
            get {
                return this.IdplaceField;
            }
            set {
                if ((object.ReferenceEquals(this.IdplaceField, value) != true)) {
                    this.IdplaceField = value;
                    this.RaisePropertyChanged("Idplace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Starttime {
            get {
                return this.StarttimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StarttimeField, value) != true)) {
                    this.StarttimeField = value;
                    this.RaisePropertyChanged("Starttime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAdmin.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doLoginAdmin", ReplyAction="http://tempuri.org/IService1/doLoginAdminResponse")]
        int doLoginAdmin(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doDeleteAdmin", ReplyAction="http://tempuri.org/IService1/doDeleteAdminResponse")]
        int doDeleteAdmin(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doUpdateAdmin", ReplyAction="http://tempuri.org/IService1/doUpdateAdminResponse")]
        int doUpdateAdmin(UKM.ServiceAdmin.Account acc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/convertukm", ReplyAction="http://tempuri.org/IService1/convertukmResponse")]
        string convertukm(string ukm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCaptain", ReplyAction="http://tempuri.org/IService1/GetCaptainResponse")]
        UKM.ServiceAdmin.Account[] GetCaptain(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doInsertCaptainAdmin", ReplyAction="http://tempuri.org/IService1/doInsertCaptainAdminResponse")]
        int doInsertCaptainAdmin(UKM.ServiceAdmin.Account acc, UKM.ServiceAdmin.StudentUKM ukm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doDeleteCoach", ReplyAction="http://tempuri.org/IService1/doDeleteCoachResponse")]
        int doDeleteCoach(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doUpdateCoach", ReplyAction="http://tempuri.org/IService1/doUpdateCoachResponse")]
        int doUpdateCoach(UKM.ServiceAdmin.Coach acc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/convertcoach", ReplyAction="http://tempuri.org/IService1/convertcoachResponse")]
        string convertcoach(string ukm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCoach", ReplyAction="http://tempuri.org/IService1/GetCoachResponse")]
        UKM.ServiceAdmin.Coach[] GetCoach(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doInsertCoach", ReplyAction="http://tempuri.org/IService1/doInsertCoachResponse")]
        int doInsertCoach(UKM.ServiceAdmin.Coach acc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doDeleteUKM", ReplyAction="http://tempuri.org/IService1/doDeleteUKMResponse")]
        int doDeleteUKM(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doUpdateUKM", ReplyAction="http://tempuri.org/IService1/doUpdateUKMResponse")]
        int doUpdateUKM(UKM.ServiceAdmin.cUkm acc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUKM", ReplyAction="http://tempuri.org/IService1/GetUKMResponse")]
        UKM.ServiceAdmin.cUkm[] GetUKM(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doInsertUKM", ReplyAction="http://tempuri.org/IService1/doInsertUKMResponse")]
        int doInsertUKM(UKM.ServiceAdmin.cUkm acc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doDeletePlace", ReplyAction="http://tempuri.org/IService1/doDeletePlaceResponse")]
        int doDeletePlace(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doUpdatePlace", ReplyAction="http://tempuri.org/IService1/doUpdatePlaceResponse")]
        int doUpdatePlace(UKM.ServiceAdmin.Place acc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/convertplace", ReplyAction="http://tempuri.org/IService1/convertplaceResponse")]
        string convertplace(string place);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPlace", ReplyAction="http://tempuri.org/IService1/GetPlaceResponse")]
        UKM.ServiceAdmin.Place[] GetPlace(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doInsertPlace", ReplyAction="http://tempuri.org/IService1/doInsertPlaceResponse")]
        int doInsertPlace(UKM.ServiceAdmin.Place acc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doDeleteSchedule", ReplyAction="http://tempuri.org/IService1/doDeleteScheduleResponse")]
        int doDeleteSchedule(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doUpdateSchedule", ReplyAction="http://tempuri.org/IService1/doUpdateScheduleResponse")]
        int doUpdateSchedule(UKM.ServiceAdmin.Schedule acc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSchedule", ReplyAction="http://tempuri.org/IService1/GetScheduleResponse")]
        UKM.ServiceAdmin.Schedule[] GetSchedule(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/doInsertSchedule", ReplyAction="http://tempuri.org/IService1/doInsertScheduleResponse")]
        int doInsertSchedule(UKM.ServiceAdmin.Schedule acc);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : UKM.ServiceAdmin.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<UKM.ServiceAdmin.IService1>, UKM.ServiceAdmin.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int doLoginAdmin(string username, string password) {
            return base.Channel.doLoginAdmin(username, password);
        }
        
        public int doDeleteAdmin(string id) {
            return base.Channel.doDeleteAdmin(id);
        }
        
        public int doUpdateAdmin(UKM.ServiceAdmin.Account acc) {
            return base.Channel.doUpdateAdmin(acc);
        }
        
        public string convertukm(string ukm) {
            return base.Channel.convertukm(ukm);
        }
        
        public UKM.ServiceAdmin.Account[] GetCaptain(string Name) {
            return base.Channel.GetCaptain(Name);
        }
        
        public int doInsertCaptainAdmin(UKM.ServiceAdmin.Account acc, UKM.ServiceAdmin.StudentUKM ukm) {
            return base.Channel.doInsertCaptainAdmin(acc, ukm);
        }
        
        public int doDeleteCoach(string id) {
            return base.Channel.doDeleteCoach(id);
        }
        
        public int doUpdateCoach(UKM.ServiceAdmin.Coach acc) {
            return base.Channel.doUpdateCoach(acc);
        }
        
        public string convertcoach(string ukm) {
            return base.Channel.convertcoach(ukm);
        }
        
        public UKM.ServiceAdmin.Coach[] GetCoach(string Name) {
            return base.Channel.GetCoach(Name);
        }
        
        public int doInsertCoach(UKM.ServiceAdmin.Coach acc) {
            return base.Channel.doInsertCoach(acc);
        }
        
        public int doDeleteUKM(string id) {
            return base.Channel.doDeleteUKM(id);
        }
        
        public int doUpdateUKM(UKM.ServiceAdmin.cUkm acc) {
            return base.Channel.doUpdateUKM(acc);
        }
        
        public UKM.ServiceAdmin.cUkm[] GetUKM(string Name) {
            return base.Channel.GetUKM(Name);
        }
        
        public int doInsertUKM(UKM.ServiceAdmin.cUkm acc) {
            return base.Channel.doInsertUKM(acc);
        }
        
        public int doDeletePlace(string id) {
            return base.Channel.doDeletePlace(id);
        }
        
        public int doUpdatePlace(UKM.ServiceAdmin.Place acc) {
            return base.Channel.doUpdatePlace(acc);
        }
        
        public string convertplace(string place) {
            return base.Channel.convertplace(place);
        }
        
        public UKM.ServiceAdmin.Place[] GetPlace(string Name) {
            return base.Channel.GetPlace(Name);
        }
        
        public int doInsertPlace(UKM.ServiceAdmin.Place acc) {
            return base.Channel.doInsertPlace(acc);
        }
        
        public int doDeleteSchedule(string id) {
            return base.Channel.doDeleteSchedule(id);
        }
        
        public int doUpdateSchedule(UKM.ServiceAdmin.Schedule acc) {
            return base.Channel.doUpdateSchedule(acc);
        }
        
        public UKM.ServiceAdmin.Schedule[] GetSchedule(string Name) {
            return base.Channel.GetSchedule(Name);
        }
        
        public int doInsertSchedule(UKM.ServiceAdmin.Schedule acc) {
            return base.Channel.doInsertSchedule(acc);
        }
    }
}
